### ISSUE TITLE
Improved Linux documentation

### ISSUE THREAD

**Issue by equist** [ActiveLogin/ActiveLogin.Authentication#290]
**Certificate problem in Linux**
I have spend some time with certificate problems when running in Linux (Docker). My initial solution was to embedd the BankId root certificates as files as Embedded resources and then read that resource. I made an byte array of the file and used that byte array as argument for X509Certificate2. Something like this:

```csharp
var assembly = typeof(AuthBuilderExtensions).Assembly;
var resourceName = $"MyNamespace.BankIdRootCertificate-{environment}.crt";

using var certStream = assembly.GetManifestResourceStream(resourceName);
using var memoryStream = new MemoryStream((int)certStream.Length);

certStream.CopyTo(memoryStream);
var bytes = memoryStream.ToArray();
return new X509Certificate2(bytes, string.Empty, X509KeyStorageFlags.MachineKeySet);
```

This works perfectly on Windows, but fails with the following Exception in Linux:

```
System.Security.Cryptography.CryptographicException: ASN1 corrupted data.
 ---> System.Formats.Asn1.AsnContentException: The encoded length exceeds the maximum supported by this library (Int32.MaxValue).
   at System.Formats.Asn1.AsnDecoder.ReadLength(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& bytesConsumed)
   at System.Formats.Asn1.AsnDecoder.ReadEncodedValue(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& contentOffset, Int32& contentLength, Int32& bytesConsumed)
   at Internal.Cryptography.Pal.UnixPkcs12Reader.ParsePkcs12(ReadOnlySpan`1 data)
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.StorePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(ReadOnlySpan`1 rawData, ReadOnlySpan`1 password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
```

It took me a while before I resolved that this was the problem and I thought I could at least save other some time.

**My solution**
Instead of embedding the file as a resource, I instead stored the content between Begin certificate and End certificate in a resource file. This data is base64 encoded and on Linux it must be decoded. My code now looks like this:

```
var rootCertEncoded = CertificateResource.BankIdRootTest;
var rootCertBytes = Convert.FromBase64String(rootCertEncoded);

return new X509Certificate2(rootCertBytes, (System.Security.SecureString)null, X509KeyStorageFlags.MachineKeySet);
```

Less code and simpel to read.

**What area is it related to**
BankId documentation.

**Describe the solution you'd like**
Maybe this could be added to the Readme or at least exists here in the issue tracker if someone else gets this problem.

**Comment by PeterOrneholm** [comment]
Thanks for highlighting this Eric!

I would propose you make a PR updating the FAQ at the bottom [here](https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/master/docs/getting-started-bankid.md). Write a short summary on the issue, an overview of the solution and refer to this issue for all the details.
